Repository kamp-us/monorepo, pull requests merged in 2023-08, with the labels that each got.

#572 Connect pano to GQL
  .github/workflows/ci.yml
  apps/gql/.env.example
  apps/gql/actions.ts
  apps/gql/app/graphql/route.ts
  apps/gql/env.ts
  apps/gql/features/errors/index.ts
  apps/gql/features/pano/post.ts
  apps/gql/features/pano/utils/get-sitename.test.ts
  apps/gql/features/pano/utils/get-sitename.ts
  apps/gql/loaders/user.ts
  apps/gql/package.json
  apps/gql/schema/resolvers/index.ts
  apps/gql/schema/schema.graphql
  apps/gql/schema/types.generated.ts
  apps/gql/schema/types.ts
  apps/kampus/.env.example
  apps/kampus/app/page.tsx
  apps/kampus/env.ts
  apps/kampus/features/pasaport/components/sign-in/index.tsx
  apps/kampus/features/pasaport/components/sign-out/index.tsx
  apps/kampus/features/pasaport/components/sign-up/index.tsx
  apps/kampus/middleware.ts
  apps/kampus/next.config.mjs
  package-lock.json
  packages/next-auth/index.ts
  packages/next-auth/src/authOptions.ts
  packages/next-auth/src/session.ts
  packages/relay/environment.ts
  packages/relay/use-serializable-preloaded-query.ts
  tsconfig.json
  turbo.json
Labels: ready for review

#577 feat(app/pano):used toast component
  apps/kampus/app/layout.tsx
  apps/kampus/app/pano/features/post-list/MoreOptions.tsx
  packages/ui/components/index.ts
  packages/ui/components/toast.tsx
  packages/ui/components/toaster.tsx
Labels: pano, ready for review, apps/kampus

#605 feat(apps/gql): add post upvote mutations
  apps/gql/features/pano/index.ts
  apps/gql/features/pano/postUpvote.ts
  apps/gql/loaders/pano.ts
  apps/gql/schema/resolvers/index.ts
  apps/gql/schema/schema.graphql
  apps/gql/schema/types.generated.ts
  db/prisma/schema.prisma
Labels: apps/gql

#607 fix(apps/gql): add PostUpvote resolver & update PostUpvote graphql fields
  apps/gql/loaders/pano.ts
  apps/gql/schema/resolvers/index.ts
  apps/gql/schema/schema.graphql
  apps/gql/schema/types.generated.ts
Labels: apps/gql

#579 feat (apps/pano): use dialog for post deletion
  apps/kampus/app/pano/features/post-list/MoreOptions.tsx
Labels: ready for review

#629 feat(apps/pano): show "Duzenle" and "Sil" on more options for the post
  apps/kampus/app/pano/PanoFeed.tsx
  apps/kampus/app/pano/PostListContainer.tsx
  apps/kampus/app/pano/__generated__/PanoFeedFragment.graphql.ts
  apps/kampus/app/pano/__generated__/PanoFeedPaginationQuery.graphql.ts
  apps/kampus/app/pano/__generated__/PanoFeed_viewer.graphql.ts
  apps/kampus/app/pano/__generated__/PostListContainerQuery.graphql.ts
  apps/kampus/app/pano/features/post-list/MoreOptions.tsx
  apps/kampus/app/pano/features/post-list/PostItem.tsx
  apps/kampus/app/pano/features/post-list/__generated__/MoreOptionsRemovePostMutation.graphql.ts
  apps/kampus/app/pano/features/post-list/__generated__/MoreOptions_post.graphql.ts
  apps/kampus/app/pano/features/post-list/__generated__/MoreOptions_viewer.graphql.ts
  apps/kampus/app/pano/features/post-list/__generated__/PostItem_post.graphql.ts
  apps/kampus/app/pano/features/post-list/__generated__/PostItem_viewer.graphql.ts
Labels: ready for review

#638 feat(pano): add create post form with modal route ux
  apps/kampus/app/pano/@modal/(.)post/create/page.tsx
  apps/kampus/app/pano/@modal/(.)post/default.tsx
  apps/kampus/app/pano/@modal/default.tsx
  apps/kampus/app/pano/CreatePanoPostForm.tsx
  apps/kampus/app/pano/PanoFeed.tsx
  apps/kampus/app/pano/__generated__/CreatePanoPostFormMutation.graphql.ts
  apps/kampus/app/pano/__generated__/PanoFeedPaginationQuery.graphql.ts
  apps/kampus/app/pano/__generated__/PostListContainerQuery.graphql.ts
  apps/kampus/app/pano/features/post-list/MoreOptions.tsx
  apps/kampus/app/pano/features/post-list/PostItem.tsx
  apps/kampus/app/pano/features/post-list/PostUpvoteButton.tsx
  apps/kampus/app/pano/features/post-list/__generated__/PostItem_post.graphql.ts
  apps/kampus/app/pano/layout.tsx
  apps/kampus/app/pano/post/create/page.tsx
  apps/kampus/app/pano/post/default.tsx
  package-lock.json
  packages/tailwind/plugin.ts
  packages/ui/components/button.tsx
  packages/ui/components/dialog.tsx
Labels: work in progress
